version: 1
services:
  - type: web
    name: my-react-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    rewrites:
      - source: /*
        destination: /index.html
