const CLOUDINARY_BASE_URL = process.env.REACT_APP_CLOUDINARY_BASE_URL;
const BLOG_APP_FOLDER = process.env.REACT_APP_CLOUDINARY_BLOG_APP_FOLDER;

const UPLOAD_FOLDER_BASE_URL = `${CLOUDINARY_BASE_URL}/${BLOG_APP_FOLDER}/`;
const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;

const stables = { UPLOAD_FOLDER_BASE_URL, API_BASE_URL };

export default stables;
